name: Build, Push, and Deploy Docker App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Google Cloud (use secrets for GCP credentials)
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}  # The full Workload Identity Provider URL
          service_account: github-actions@fin1-433309.iam.gserviceaccount.com  # The service account email you're assuming
          audience: "projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }} .

      # Step 5: Push Docker image to Google Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }}

      # Step 6: Deploy the Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy node-sample-app \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: us-central1
