name: Build, Push, and Deploy Docker App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Google Cloud (use secrets for GCP credentials)
      - name: Log in to Google Cloud
        run: |
          # Decode the base64-encoded service account key and write it to a temporary file
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 --decode > /tmp/gcloud-service-key.json

          # Authenticate using the decoded service account key
          gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json

          # Set the Google Cloud project
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          # Authenticate Docker with Artifact Registry
          gcloud auth configure-docker asia-south1-docker.pkg.dev  # for Artifact Registry

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }} .

      # Step 5: Push Docker image to Google Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }}

      # Step 6: Deploy the Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy node-sample-app \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fin1-dev/node-sample-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: us-central1
